### ISSUE TITLE
Axios interceptor doesn't work

### ISSUE THREAD

**Issue by alvaro-canepa** [martin-badin/vue-october-requests#1]
Hi, first all, great addition!

I have my axios.interceptors with `X-CSRF-TOKEN` header, but `$october.request` use a new instance of axios. Or maybe I'm making something wrong. 
How can I use my own axios instance?

thanks

**Comment by martin-badin** [comment]
Hi, thank you for your first issue.

It's correct. This plugin uses own Axios instance. I will add new options to the plugin tonight. :)

**Comment by alvaro-canepa** [comment]
Great! by the way, all callbacks are required?
If I made a simple request, like `this.$october.request('onDoSomething')`, I get error `undefined func`.

thanks!!!

**Comment by martin-badin** [comment]
`request`expected object, not the string.

For example: 
```
this.$october.request({
  handler: "onSubmit",
  formData
  // onLoading: onLoading,
  // onError: onError,
  // onSuccess: onSuccess,
  // redirect: "/"
});
```

**Comment by martin-badin** [comment]
I added new option to the plugin
```
export interface PluginOptions {
  readonly axios: AxiosStatic;
  readonly timeout?: number;
  readonly headers?: Readonly<Record<string, string>>;
}
```

**Comment by alvaro-canepa** [comment]
Thanks!!!
